from django.urls import path

from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('accounts/login/', views.PlannerLoginView.as_view(), name='login'),
    path('accounts/logout/', views.logout_page, name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('goals/', views.goal_list, name='goal_list'),
    path('goals/new/', views.goal_create, name='goal_create'),
    path('goals/<int:goal_id>/', views.goal_detail, name='goal_detail'),
    path('goals/<int:goal_id>/edit/', views.goal_edit, name='goal_edit'),
    path('goals/<int:goal_id>/delete/', views.goal_delete, name='goal_delete'),
    path('goals/<int:goal_id>/milestones/new/', views.milestone_create, name='milestone_create'),
    path('goals/<int:goal_id>/sessions/new/', views.session_create, name='goal_session_create'),
    path('goals/<int:goal_id>/notes/new/', views.progress_note_create, name='goal_note_create'),
    path('milestones/<int:milestone_id>/edit/', views.milestone_edit, name='milestone_edit'),
    path('milestones/<int:milestone_id>/delete/', views.milestone_delete, name='milestone_delete'),
    path('sessions/', views.session_list, name='session_list'),
    path('sessions/new/', views.session_create, name='session_create'),
    path('sessions/<int:session_id>/edit/', views.session_edit, name='session_edit'),
    path('sessions/<int:session_id>/delete/', views.session_delete, name='session_delete'),
    path('notes/', views.progress_note_list, name='progress_note_list'),
    path('notes/new/', views.progress_note_create, name='progress_note_create'),
    path('notes/<int:note_id>/edit/', views.progress_note_edit, name='progress_note_edit'),
    path('notes/<int:note_id>/delete/', views.progress_note_delete, name='progress_note_delete'),
    path('api/auth/register/', views.AuthRegisterAPIView.as_view(), name='api_auth_register'),
    path('api/auth/login/', views.AuthLoginAPIView.as_view(), name='api_auth_login'),
    path('api/auth/refresh/', views.AuthRefreshAPIView.as_view(), name='api_auth_refresh'),
    path('api/auth/logout/', views.AuthLogoutAPIView.as_view(), name='api_auth_logout'),
    path('api/auth/me/', views.AuthMeAPIView.as_view(), name='api_auth_me'),
    path('api/milestones/<int:milestone_id>/toggle/', views.api_milestone_toggle, name='api_milestone_toggle'),
    path('api/milestones/reorder/', views.api_milestone_reorder, name='api_milestone_reorder'),
    path('api/sessions/<int:session_id>/status/', views.api_session_status, name='api_session_status'),
    path('api/dashboard/summary/', views.api_dashboard_summary, name='api_dashboard_summary'),
]
