# Generated by Django 5.2.15 on 2026-06-13 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='planner.goal')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('RESCHEDULED', 'Rescheduled')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='planner.goal')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='planner.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='planner.goal')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_notes', to='planner.milestone')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_notes', to='planner.practicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='planner_goa_user_id_4691d3_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'priority'], name='planner_goa_user_id_52bf23_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['target_date'], name='planner_goa_target__640535_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['created_at'], name='planner_goa_created_0c1c09_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'order'], name='planner_mil_goal_id_c9874d_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['due_date'], name='planner_mil_due_dat_12bdfa_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['is_complete'], name='planner_mil_is_comp_1033f3_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['created_at'], name='planner_mil_created_1a4a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'status'], name='planner_pra_user_id_018926_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['goal', 'status'], name='planner_pra_goal_id_d36410_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['scheduled_for'], name='planner_pra_schedul_cfda9d_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['created_at'], name='planner_pra_created_1629f4_idx'),
        ),
        migrations.AddIndex(
            model_name='progressnote',
            index=models.Index(fields=['user', 'created_at'], name='planner_pro_user_id_f95e27_idx'),
        ),
        migrations.AddIndex(
            model_name='progressnote',
            index=models.Index(fields=['goal', 'created_at'], name='planner_pro_goal_id_43d418_idx'),
        ),
        migrations.AddIndex(
            model_name='progressnote',
            index=models.Index(fields=['created_at'], name='planner_pro_created_d69398_idx'),
        ),
    ]
